# Generated by Django 4.0.1 on 2022-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_project_heading_alter_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='property',
            new_name='projects',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, default='project_images/default_project.jpg', null=True, upload_to='project_images/'),
        ),
    ]
