# Generated by Django 4.0.1 on 2022-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_image_alter_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
