# Generated by Django 4.0.1 on 2022-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
