# Generated by Django 4.0.1 on 2022-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, default='static/project_images/default_project.jpg', null=True, upload_to='static/project_images/'),
        ),
    ]
