# Generated by Django 4.0.1 on 2022-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_rank_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, default='project_images/default_project.jpg', null=True, upload_to='project_images/'),
        ),
    ]
